### ISSUE TITLE
Library to install applications on Windows Sandbox

### ISSUE THREAD

**Issue by hasan-hasanov** [TomasHubelbauer/windows-sandbox-script#1]
Hi, 

Sorry to bother you but I noticed that we currently are doing a similar thing. 
I have created a library that executes a script inside Windows Sandbox. 

I am currently trying to popularize it and will be grateful if you have any suggestions or some particular use case that I did not cover up.

Take a look when you have time [CLICK](https://github.com/hasan-hasanov/ScoopBox)

Best Regards

**Comment by TomasHubelbauer** [comment]
Your project looks good! I can't think of anything to add. Best of luck with ScoopBox!
